version: 0.2
env:
  shell: bash
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - npm run cdk deploy CorsApiStack -- --require-approval never